### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [EmmaOyetey/Portfolio-Project#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages)
2. A public GitHub repository for your codebase
3. Use HTML & SCSS
4. Make good use of semantic HTML elements
5. Be responsive (mobile-first) and built with accessibility in mind
6. Code is highly readable (good naming and indented correctly)

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 90 / 110 |

### Positive

- Your project is great! it has been a good exercise for you to build a website from a wireframe.
  - If you ever need a break pick a figma design and try and recreate it.
- I am glad you pushed yourself by choosing to break your styles into multiple logical files.
  - There is a little point on that below but Keep challenging yourself!
- It is good that you have added your profile picture, Keep on adding to the portfolio as you complete projects and have your profile completed.
- Great use of media queries, try using variables for the breakpoints in your next project.
  - `@media screen and (min-width: 768px) {}` -> `@media screen and (min-width: $tablet-breakpoint) {}`
- You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.
- I noticed the different themes you had in your variables file if you are interested in adding a theme toggle have a look at this (Code pen)[https://codepen.io/charlie-robin/pen/jOrBdLY] it is relatively simple to set up with a little JS.

### Constructive

- Here are some little pointers to fix for your HTML:

  - Your `<nav></nav>` tag should be inside the `<body></body>` tag.
  - I think that your `<section class="intro">` should be a `<header>` and the `<section class="external-links">` should be a `<footer>`.
  - On the live site your technical icons are not showing, only the alt text.
    - It Looks like you are just missing a "." from the src on each of them.
    - `<img src="/images/Skill=BEM.svg" alt="BEM logo" class="bem-logo" />` -> `<img src="./images/Skill=BEM.svg" alt="BEM logo" class="bem-logo" />`
    - Have a look at the [A target attribute](https://www.w3schools.com/tags/att_a_target.asp) you can use this to launch the links to your projects in a new tab.

- I like that you have started to group your styles into a folder it is a little bit confusing that you have two of each file one in a `code` folder and another in the root of the project. If you want to use the styles from the folder in your `main.scss` you can give it the path and it should do the rest.

  - `@use "./base" ;` -> `@use "./code/base";`
  - I am not sure which file to give you feedback back so will go for the files in the root of the project.

- You can use a modifier with a block and I think you have a good example with your headings when to do so.
  - Instead of `heading__aboutMe` you would have `heading--about-me` this means you can group all of your heading styles into your block and use modifiers to make any tweaks on the individual headings.

```scss
// CURRENT CODE
.heading__aboutMe {
  font-family: $heading-font-family;
  background-color: $color-background-main;
  color: $color-text-black;
  text-align: center;
  font-size: 16px;
  font-weight: 500;
  padding: 5px;
}

.heading__myPortfolio {
  font-family: $heading-font-family;
  background-color: $color-background-black;
  color: $color-text-white;
  text-align: center;
  font-weight: 400;
  font-size: 18px;
  padding: 5px;
  margin-top: 10px;
  margin-bottom: 10px;
}

// COULD BE

.heading {
  font-family: $heading-font-family;
  text-align: center;
  background-color: $color-background-main;
  color: $color-text-black;
  // MAKE SURE IT IS ALWAYS LOWERCASE HYPHENATED
  // - CAMEL CASE IS FOR JS, aboutMe -> about-me
  &--about-me {
    font-size: 16px;
    font-weight: 500;
    padding: 5px;
  }

  &--my-portfolio {
    background-color: $color-background-black;
    color: $color-text-white;
    font-weight: 400;
    font-size: 18px;
    padding: 5px;
    margin-top: 10px;
    margin-bottom: 10px;
  }
}
```

- I like the use of a background image kudos for researching this and also the linear gradient effect :). From a UI perspective, it is competing with the content slightly on smaller devices. Ideally, you want the text and projects to be clearer.
  - Have a look at [Toptal Subtle Patterns](https://www.toptal.com/designers/subtlepatterns/) for some free muted background patterns.

---
